version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run:
          name: Copy Repo
          command: git clone --recursive git@github.com:grigdav/smartgarden_webapp.git
      - run:
          name:  Deploy Repo
          command: echo -ne '\n' | scp -r * ssh david.grigoryev@89.108.84.191:/var/www/test_dir/
